### ISSUE TITLE
看了您《基于GAN的无监督机器音频异常检测与定位》的报告后有几个问题想请教您

### ISSUE THREAD

**Issue by 6868king** [jianganbai/AEGAN-AD#1]
尊敬的姜安柏博士：
       您好！
       非常感谢您的在机器音频异常检测工作上的贡献，听完您的报告，我有几个问题想请教一下您。
       1.生成器的损失函数中的feature-matching Loss部分，为什么要加上判别器中间隐藏层的真实数据和重构数据均值差的范数的平方，还有方差的差的范数的平方，这样做起到了什么作用？为什么要选择在判别器隐藏层？这里选择的是中间的哪个隐藏层的输出？

       2.生成器部分的重构误差的设置中，将重构数据输入到encoder得到的维度为256的特征向量和真实数据的256特征向量对比，这个差异可以解释一下具体体现的是什么吗？将这个加到整个重构误差中起到了什么作用呢？

       如果您能解答我的疑惑，我将不胜感激。感谢您在百忙之中阅读我的邮件，谢谢！
       
        祝您生活愉快，科研顺利！

**Comment by jianganbai** [comment]
您好！感谢对我们组工作的关注。

1. feature-matching loss部分比较中间层统计量，是为了获得判别器对谱特征层面上的判断，这样梯度反传时，生成器可按判别器的指导更新，重构出的谱不仅仅MSE小，特征也更像。我们发现有的机器适合只比较均值，有的适合比较均值和方差。选择在隐藏层是因为隐藏层包含了谱的特征信息，一般都从隐藏层提取embedding，AEGAN-AD中提取的是最后一个卷积层的输出。

2. 隐空间的重构误差仅用于检测阶段。我们发现Autoencoder的隐空间整合了谱的特征，同时训练时也没对这部分进行约束，因而谱的特征会更自然。隐空间的重构误差其实是特征层面的重构误差，某些机器上会比谱的MSE更好。

祝好！

**Comment by 6868king** [comment]
谢谢您，收获很多

**Comment by 6868king** [comment]
谢谢您，收获很多




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianganbai/AEGAN-AD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月1日(星期四) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jianganbai/AEGAN-AD] 看了您《基于GAN的无监督机器音频异常检测与定位》的报告后有几个问题想请教您 (Issue #1)





 
您好！感谢对我们组工作的关注。
  
 
feature-matching loss部分比较中间层统计量，是为了获得判别器对谱特征层面上的判断，这样梯度反传时，生成器可按判别器的指导更新，重构出的谱不仅仅MSE小，特征也更像。我们发现有的机器适合只比较均值，有的适合比较均值和方差。选择在隐藏层是因为隐藏层包含了谱的特征信息，一般都从隐藏层提取embedding，AEGAN-AD中提取的是最后一个卷积层的输出。
 
 
 
隐空间的重构误差仅用于检测阶段。我们发现Autoencoder的隐空间整合了谱的特征，同时训练时也没对这部分进行约束，因而谱的特征会更自然。隐空间的重构误差其实是特征层面的重构误差，某些机器上会比谱的MSE更好。
 
  
祝好！
