### ISSUE TITLE
请教代码相关问题

### ISSUE THREAD

**Issue by yangshumeiyangshumei** [jianganbai/AEGAN-AD#11]
尊敬的姜博士您好：
       看了您的论文，跑了一下这个DCASE2022的代码，我用的显卡RTX 4090, 在config.yaml中也替换了pretain中的参数，其他是没有变的，为什么bearing的效果还是不行呢，这是正常情况吗？
![跑的结果参数](https://github.com/jianganbai/AEGAN-AD/assets/128444781/fd236a76-8dc1-4016-8e2b-385307598c53)

![跑的结果](https://github.com/jianganbai/AEGAN-AD/assets/128444781/a742d8a8-e085-430a-869f-4bd1d56d3591)

**Comment by jianganbai** [comment]
你好，AEGAN在bearing上的波动程度是会大一些。

你可以先试试pre-train checkpoint，判断是config没配置对，还是碰巧这个seed不好。

**Comment by yangshumeiyangshumei** [comment]
seed 用的783，config.yaml刚刚检查了一下是跟pretrain里面的bearing_cfg.yaml参数是一样的。
