### ISSUE TITLE
请教数据集划分问题

### ISSUE THREAD

**Issue by yangshumeiyangshumei** [jianganbai/AEGAN-AD#12]
尊敬的姜博士：
      您好，关于您的代码，我想问一下对于不同数据集，您说训练的数据是不一样的，那对于用deval进行训练时，都是怎么划分的数据集呢？是dev_data和eval_data里面训练数据的集合吗？还是有比例的？代码中并没有看到具体是怎么划分的deval数据集呢。作为学术小白，可以回答一下我的问题嘛，谢谢您！
     祝您一切顺遂！

**Comment by jianganbai** [comment]
你好，感谢对我们工作的关注。

20/22数据集，dev和eval都有相同的机器类型（例如：dev和eval都有fan这种机器）。

"deval"指的是，把同一类机器在dev和eval的全部数据，都拿来训。

AEGAN-AD是对每类不同机器单独训一个模型。

祝好。

**Comment by yangshumeiyangshumei** [comment]
好的谢谢您

**Comment by yangshumeiyangshumei** [comment]
不好意思还想问一下，关于生成deval数据集的训练集和测试集的代码有嘛？我在代码中没有发现呢，可以跟我说一下嘛，谢谢您！

**Comment by jianganbai** [comment]
20年和22年的数据集，都定义在相应目录的datasets.py里面

**Comment by yangshumeiyangshumei** [comment]
好的好的谢谢您，祝您事事顺心，身体健康。
