### ISSUE TITLE
对一个音频进行推理

### ISSUE THREAD

**Issue by zyb8543d** [jianganbai/AEGAN-AD#2]
怎么对一个音频进行推理，并获得得分，判别是正常还是异常？

**Comment by jianganbai** [comment]
你好！

在AEGAN-AD框架中，我们先计算10s音频的mel谱，再用滑动窗口截取出有重叠的片段，再将这些片段送入G网络或D网络中。

G网络重构输入的mel谱片段，重构误差为异常分数。重构误差一方面衡量重构谱和原始谱的差异，另一方面将重构谱送回G网络的encoder中，获得隐空间的重构误差。最后，我们沿时间轴取min/max/sum，获得整个谱的异常分数。

D网络分别提取各片段的embedding，然后将同段10s音频的不同embedding取平均，作为这段音频的表征。我们使用KNN, LOF和到训练样本的中心的距离，获得音频embedding的异常分数。

对于不同机器，我们选择最适合的异常分数。若分数超过某个阈值，则认为是异常。

希望这段解释能帮助到你。
