### ISSUE TITLE
运行代码后效果不是很理想

### ISSUE THREAD

**Issue by wyk777777** [jianganbai/AEGAN-AD#4]
大佬你好
我下载代码后，跑了一下22年的数据集，但是跑出来的结果不是很理想。
配置文件中仅修改了随机种子（默认种子也尝试过）和data_set_dir的路径
<img width="459" alt="image" src="https://github.com/jianganbai/AEGAN-AD/assets/129475092/94d5f811-d2ca-458d-8100-ad108687200c">
（左边是我跑出来的结果）
我尝试了修改学习率但是效果还是差不多。刚入门深度学习，不知道这种差异可能是哪些原因造成的。能指点一下吗QAQ

**Comment by jianganbai** [comment]
您好！

主要原因应该是没有使用pretrain子文件中的给出的config超参数，需要使用这些超参数替换掉原始的config.yaml。

例如gearbox表现差，应该是还用的LN归一化，但我们在实验中发现BN对gearbox更好。bearing表现差，应该是没有用dev+eval集一块训。

还有一个可能的原因是显卡不一致，固定了seed可能也会有一定差异。我们使用的显卡是RTX 3090。

异常检测模型本身就不稳定，与数据分布强相关，换用不同超参数，结果相差5%比较常见。

**Comment by wyk777777** [comment]
好的 感谢回复

**Comment by challenge-my** [comment]
> 好的 感谢回复



> 大佬你好 我下载代码后，跑了一下22年的数据集，但是跑出来的结果不是很理想。 配置文件中仅修改了随机种子（默认种子也尝试过）和data_set_dir的路径 <img alt="image" width="459" src="https://user-images.githubusercontent.com/129475092/249156096-94d5f811-d2ca-458d-8100-ad108687200c.png"> （左边是我跑出来的结果） 我尝试了修改学习率但是效果还是差不多。刚入门深度学习，不知道这种差异可能是哪些原因造成的。能指点一下吗QAQ

您好，请问您运行姜博士代码时有没有报错哇，报错是KeyError: 'graph_hop_f'？谢谢

**Comment by wyk777777** [comment]
作者你好
我近期发现bearing数据集中的训练集数量为2999（本应该为3000），在官网多次重新下载解压后数据集数量仍然不对，不知道你本地训练时数据集数量是否正常？
感谢

**Comment by jianganbai** [comment]
你好，22年部分机器确实不是正好3000条

**Comment by wyk777777** [comment]
好的 十分感谢你的回复
