### ISSUE TITLE
请问一下20的数据集您使用的是什么指标。

### ISSUE THREAD

**Issue by Dubu-Q** [jianganbai/AEGAN-AD#5]
主页展示的那个20年的表格中用的是auc还是pauc？谢谢您的回答。

**Comment by jianganbai** [comment]
你好，那个是AUC和pAUC取平均后的结果

**Comment by Dubu-Q** [comment]
> 你好，那个是AUC和pAUC取平均后的结果

是(auc+pauc)/2吗
