### ISSUE TITLE
有一些关于代码的问题想请教您

### ISSUE THREAD

**Issue by challenge-my** [jianganbai/AEGAN-AD#6]
尊敬的姜博士您好：
          我在下载您的代码后，按您说的命令运行DC2020年代码，首先报错是提示没有“  graph_hop_f”这个键，然后我对比22年的代码，在yaml文件中添加了  graph_hop_f: 1，然后继续运行，然后报错了，提示信息是assert status_note in ['normal', 'anomaly']
AssertionError，具体信息如下图，请问这个原因是什么呀？谢谢
![image](https://github.com/jianganbai/AEGAN-AD/assets/58450648/87c722b0-5fa9-4b07-8f58-c5d3acbb3f5e)
![image](https://github.com/jianganbai/AEGAN-AD/assets/58450648/11ef2774-cb9f-4c3b-aaef-27a63dda8df4)

请问是我运行代码的方式不对吗？

祝您一切顺利

**Comment by jianganbai** [comment]
你好！yaml文件里确实缺少graph_hop_f 这个key，已更新代码，感谢指正。

assert status_note可能是数据集的路径没有设对，需要yaml文件里自行设置数据集的路径

**Comment by challenge-my** [comment]
谢谢您，已跑通，祝您一切顺利
