### ISSUE TITLE
我想请教一下您这篇论文训练的时候用了附加训练集吗？测试的时候用的是开发集的test数据吗？

### ISSUE THREAD

**Issue by fanxiaoxiaoxin** [jianganbai/AEGAN-AD#7]
尊敬的姜安柏博士：
您好！
看完您的论文，我有几个问题想请教一下您！
我想请教一下您这篇论文训练的时候用了附加训练集吗？测试的时候用的是开发集的test数据吗？
祝好！

**Comment by jianganbai** [comment]
你好！

训练数据具体可以看一下pretrain目录的yaml文件，有的机器只用了dev集，有的机器用了dev + eval。

测试集都是dev集的test数据
