### ISSUE TITLE
您好，我在跑22年的代码时，出现了莫名的报错

### ISSUE THREAD

**Issue by challenge-my** [jianganbai/AEGAN-AD#8]
您好，是这样的，我再跑22年的时，只更换了数据集，但是跑着跑着出现了这样的一个问题，请问这个是什么原因引起的呢？谢谢![Snipaste_2023-12-08_10-53-46](https://github.com/jianganbai/AEGAN-AD/assets/58450648/732857a3-3215-4c38-a40d-be8ba776a7b7)

**Comment by jianganbai** [comment]
你好，我这边没有复现出这个问题。

可能是你对代码进行了一定修改导致的

![image](https://github.com/jianganbai/AEGAN-AD/assets/50263321/6630174b-1db6-4662-b8c0-0df8d15ee16a)

可能是这个地方把range改错了

**Comment by challenge-my** [comment]
姜博士您好，我再次检查了一下，我只修改了dc2022的数据集路径，其他没有修改，而且比较让人纳闷的一点是：在跑22年的数据时，只有fan这个类跑不了，会报这个错，其他的几类都不会报这个错，都可以顺利跑通，
![image](https://github.com/jianganbai/AEGAN-AD/assets/58450648/233db574-d798-4c25-aeb2-a33a3f41fe1f)
请问姜博士这个是什么原因？谢谢~

**Comment by jianganbai** [comment]
你可以在你的132行设一个断点，比较一下`train_set.all_clip_spec.shape`和`train_set.all_attri.shape`两个值。

正常情况下，`train_set.all_clip_spec.shape`为`(6000, 128, 13)`，`train_set.all_attri.shape`为`(6000, 5)`

**Comment by challenge-my** [comment]
尊敬的姜博士您好：
   我这两天又重新检查了一下，发现是之前的频谱路径没改，所以数据搞乱了，目前已经修复，谢谢姜博士，祝姜博士学业顺利~

**Comment by BosserWang** [comment]
> 尊敬的姜博士您好： 我这两天又重新检查了一下，发现是之前的频谱路径没改，所以数据搞乱了，目前已经修复，谢谢姜博士，祝姜博士学业顺利~

请问你说的频谱路径是哪个呀，是config.yaml中的dataset_dir嘛，期待您的答复
