### ISSUE TITLE
关于代码运行速度的问题想请教下您

### ISSUE THREAD

**Issue by challenge-my** [jianganbai/AEGAN-AD#9]
尊敬的姜博士您好：
                   请问您当时训练这个22年的模型，训练一次大约需要多久哇，我在一张4090（显存24G）上跑两个类，比如风扇和gearbox（因为我发现一个类只占显存大约10G），所以我是两个程序一起在一张4090上跑，但特别慢，有时候gearbox一个epoch需要24000秒，而风扇一个epoch需要36000秒，请问您当时运行一个类，大约跑了多久呀？谢谢
![image](https://github.com/jianganbai/AEGAN-AD/assets/58450648/af88a321-5175-4b84-825c-1d1344c2b712)
![image](https://github.com/jianganbai/AEGAN-AD/assets/58450648/be131bed-ed0b-41b7-9b8e-71d46555a580)

**Comment by jianganbai** [comment]
你好，我当时是在3090上训的模型，单卡训一个模型的时候大概1个epoch 600s左右（fan和gearbox都差不多），叠两个模型的时候大概1200s-1800s

**Comment by challenge-my** [comment]
好的，谢谢您
